version: '3'

volumes:
  mysql_data: {}

services:
  app:
    container_name: zingat
    build: .cloud/php
    image: app-zingat
    ports:
      - "9096:9000"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www:cached
    networks:
      - zingat_network

  nginx:
    container_name: zingat.nginx
    image: nginx
    ports:
      - "8096:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www:cached
    depends_on:
      - app
    networks:
      - zingat_network

  mysql:
    container_name: zingat.mysql
    image: mysql:5.7
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: zingat
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: zingat
      MYSQL_PASSWORD: 1234
    volumes:
      - .cloud/mysql/data:/var/lib/mysql
    networks:
      - zingat_network

  redis:
    container_name: zingat.redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - zingat_network

  elasticsearch:
    container_name: zingat.elasticsearch
    build: .cloud/elasticsearch/
    volumes:
      - .cloud/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:cached
      - .cloud/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.flood_stage=200mb
      - cluster.routing.allocation.disk.watermark.low=500mb
      - cluster.routing.allocation.disk.watermark.high=300mb
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - zingat_network

networks:
  zingat_network:
    driver: bridge